[general]
import = ["~/.config/alacritty/themes/themes/one_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 10
decorations = "Buttonless"

[mouse]
hide_when_typing = true

[font]
normal.family = "MesloLGL Nerd Font Mono"
size = 11

[keyboard]
bindings = [
  { key = "W", mods = "Command", action = "None" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
  { key = "Right", mods = "Alt", chars = "\u001BF" },
]
