require('rodneylab/tree')
require('rodneylab/telescope')
require('rodneylab/lightline')
require('rodneylab/gitsigns')
require('rodneylab/lsp')
require('rodneylab/treesitter')
require('rodneylab/catppuccin')
require('rodneylab/filetype')
require('rodneylab/neovide')
require('rodneylab/display')
require('rodneylab/nvim-autopairs')
require('rodneylab/trouble')

